### ISSUE TITLE
Can't encode u'u\2212'

### ISSUE THREAD

**Issue by paulomarcondes** [nschloe/matplotlib2tikz#10]
when using ipython 0.11 on Python 2.7.2 from debian sid, this simple script 
```python 
from matplotlib2tikz import save as tikz_save
x=linspace(-2,2,100)
plot(x,x**4+x**3+x**2+x)
tikz_save('teste1.tex')```

fails with error:

UnicodeEncodeError                        Traceback (most recent call last)
/home/pmarc/Dropbox/mestrado/script/<ipython-input-5-4951c59800c1> in <module>()
----> 1 tikz_save('teste1.tex')

/usr/local/lib/python2.7/dist-packages/matplotlib2tikz.pyc in save(filepath, figurewidth, figureheight, textsize, tex_relative_path_to_data, strict, draw_rectangles, wrap, extra)
    146         file_handle.write( "\n\n" )
    147 
--> 148     file_handle.write( ''.join(content) )
    149     if wrap:
    150         file_handle.write( "\\end{tikzpicture}" )

UnicodeEncodeError: 'ascii' codec can't encode character u'\u2212' in position 232: ordinal not in range(128)

The LaTeX system is the full instalation of TeXlive. (package texlive-full)

**Comment by nschloe** [comment]
Fixed.

**Comment by GillesC** [comment]
I encounterd this issue still.

```
Traceback (most recent call last):
  File "c:/Users/Calle/Documents/GitHub/DominantDirectionsIndoor/main.py", line 229, in <module>
    lm.save("min_max_spread.tex", show=True, plt=plt)
  File "c:\Users\Calle\Documents\GitHub\DominantDirectionsIndoor\LatexifyMatplotlib.py", line 140, in save
    tikzplotlib.save(out, figure=fig, textsize=8, extra_axis_parameters=extra_axis_param, float_format="{:.5f}")
  File "C:\Users\Calle\AppData\Local\Programs\Python\Python37\lib\site-packages\tikzplotlib\_save.py", line 255, in save
    file_handle.write(code)
  File "C:\Users\Calle\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2212' in position 621: character maps to <undefined>
```
