### ISSUE TITLE
On python 3.5 pip the install fails untill 'image' is installed and pillow upgraded manually.

### ISSUE THREAD

**Issue by EraYaN** [nschloe/matplotlib2tikz#112]
Before manually installing image:
```
PS C:\Users\Erwin> pip install matplotlib2tikz
Collecting matplotlib2tikz
  Using cached matplotlib2tikz-0.5.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "[.]\pip-build-aqxpc3bp\matplotlib2tikz\setup.py", line 7, in <module>
        from matplotlib2tikz import __version__, __license__, __author__, __email__
      File "[.]\pip-build-aqxpc3bp\matplotlib2tikz\matplotlib2tikz\__init__.py", line 15, in <module>
        from matplotlib2tikz.save import save
      File "[.]\pip-build-aqxpc3bp\matplotlib2tikz\matplotlib2tikz\save.py", line 7, in <module>
        from . import quadmesh as qmsh
      File "[.]\pip-build-aqxpc3bp\matplotlib2tikz\matplotlib2tikz\quadmesh.py", line 5, in <module>
        from PIL import Image
      File "c:\python35\lib\site-packages\PIL\Image.py", line 66, in <module>
        from PIL import _imaging as core
    ImportError: cannot import name '_imaging'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in [.]\pip-build-aqxpc3bp\matplotlib2tikz\
```

Then I did `pip install image` and `pip install pillow --upgrade` That last one was needed to upgrade pillow to 3.3.1 from 3.1.0

The output afterward:
```
Collecting matplotlib2tikz
  Using cached matplotlib2tikz-0.5.11.tar.gz
Building wheels for collected packages: matplotlib2tikz
  Running setup.py bdist_wheel for matplotlib2tikz ... done
  Stored in directory: C:\Users\Erwin\AppData\Local\pip\Cache\wheels\59\0d\82\ed1dfcd5f6bfe068bde12b7280872a25c10b0bd0962ec1a682
Successfully built matplotlib2tikz
Installing collected packages: matplotlib2tikz
Successfully installed matplotlib2tikz-0.5.11
```

It seems like there are some incomplete deps in the package.

**Comment by nschloe** [comment]
Sounds like an issue with Pillow that's been fixed in the meantime; mpl2tikz never imports `_imaging` directly. We could of course raise the version requirement to 3.3.1, but probably it isn't mpl2tikz's job to maintain a list of bug-free dependencies. What do you think?

**Comment by nschloe** [comment]
Closing; feel free to reopen.
