### ISSUE TITLE
missing dependency on PIL/Pillow

### ISSUE THREAD

**Issue by christiankerl** [nschloe/matplotlib2tikz#116]
when installing via pip without installed Pillow library I get the following error:

``` shell
$ sudo pip3 install matplotlib2tikz
Downloading/unpacking matplotlib2tikz
  Downloading matplotlib2tikz-0.5.12.tar.gz
  Running setup.py (path:/tmp/pip_build_root/matplotlib2tikz/setup.py) egg_info for package matplotlib2tikz
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/matplotlib2tikz/setup.py", line 7, in <module>
        from matplotlib2tikz import __version__, __license__, __author__, __email__
      File "/tmp/pip_build_root/matplotlib2tikz/matplotlib2tikz/__init__.py", line 15, in <module>
        from matplotlib2tikz.save import save
      File "/tmp/pip_build_root/matplotlib2tikz/matplotlib2tikz/save.py", line 6, in <module>
        from . import image as img
      File "/tmp/pip_build_root/matplotlib2tikz/matplotlib2tikz/image.py", line 6, in <module>
        import PIL
    ImportError: No module named 'PIL'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/matplotlib2tikz/setup.py", line 7, in <module>

    from matplotlib2tikz import __version__, __license__, __author__, __email__

  File "/tmp/pip_build_root/matplotlib2tikz/matplotlib2tikz/__init__.py", line 15, in <module>

    from matplotlib2tikz.save import save

  File "/tmp/pip_build_root/matplotlib2tikz/matplotlib2tikz/save.py", line 6, in <module>

    from . import image as img

  File "/tmp/pip_build_root/matplotlib2tikz/matplotlib2tikz/image.py", line 6, in <module>

    import PIL

ImportError: No module named 'PIL'
```

after installing Pillow manually with `sudo pip3 install Pillow` the above command succeeds. so I guess matplotlib2tikz should mention Pillow as dependency?

**Comment by nschloe** [comment]
Thanks for the report.

I just released the fix (0.5.13).

**Comment by kjyv** [comment]
This still seems to be an issue with 0.5.16:

```
Collecting matplotlib2tikz
  Downloading matplotlib2tikz-0.5.16.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-mdbldt0p/matplotlib2tikz/setup.py", line 7, in <module>
        from matplotlib2tikz import __version__, __license__, __author__, __email__
      File "/private/tmp/pip-build-mdbldt0p/matplotlib2tikz/matplotlib2tikz/__init__.py", line 15, in <module>
        from matplotlib2tikz.save import save
      File "/private/tmp/pip-build-mdbldt0p/matplotlib2tikz/matplotlib2tikz/save.py", line 6, in <module>
        from . import image as img
      File "/private/tmp/pip-build-mdbldt0p/matplotlib2tikz/matplotlib2tikz/image.py", line 6, in <module>
        import PIL
    ImportError: No module named 'PIL'
```

**Comment by nschloe** [comment]
We might have to change `requires` to `install_requires` in `setup.py`. Just reading up on this.

**Comment by nschloe** [comment]
Fixed again. :smile:
