### ISSUE TITLE
3D plots

### ISSUE THREAD

**Issue by whllnd** [nschloe/matplotlib2tikz#119]
Hi,

trying to plot in 3D gives an error:
```
pos = np.zeros((3,10))
pos[0] = np.arange(10)
ax = plt.gca(projection="3d")
ax.scatter(pos[0], pos[1], pos[2], c=np.arange(pos.shape[1]))
tikz.save("../thesis/plots/pos1.tex")
```
results in
```
file encoding: UTF-8
Traceback (most recent call last):
  File "makePlots.py", line 128, in <module>
    tikz.save("../thesis/plots/pos1.tex")
  File "/home/per/.miniconda3/lib/python3.5/site-packages/matplotlib2tikz/save.py", line 146, in save
    data, content = _recurse(data, figure)
  File "/home/per/.miniconda3/lib/python3.5/site-packages/matplotlib2tikz/save.py", line 223, in _recurse
    ax = axes.Axes(data, child)
  File "/home/per/.miniconda3/lib/python3.5/site-packages/matplotlib2tikz/axes.py", line 149, in __init__
    assert yaxis_pos == 'right'
AssertionError
```
Is 3D plotting supported at all, or do I have to venture further? Great work, though, 2D plots are a real treat with this one!

```

**Comment by nschloe** [comment]
Should definitely; I'll look at it later.

**Comment by nschloe** [comment]
Perhaps an mpl issue; see https://github.com/matplotlib/matplotlib/issues/7243.

**Comment by TKaluza** [comment]
Is this the same problem? If needed I can also provide the data or try to do a MWE!
Trying to export a 3D Scatter Plot and Problems occurs:
## Input
```
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np
from matplotlib2tikz import save as tikz_save
%matplotlib notebook
data = np.genfromtxt('E-Motoren2.csv', delimiter=';', skip_header=2, names=['A', 'B', 'C', 'D'])
fig = plt.figure()#figsize=(12, 6.0))
ax = fig.add_subplot(111, projection='3d')
ax.scatter(data['A'], data['B'], data['C'],c=data['D'])
ax.set_xlabel('Durchmesser')
ax.set_ylabel('Drehzahl')
ax.set_zlabel('Ausgangsleistung')
#plt.autoscale(enable=True)
plt.show()
tikz_save('mytikz.tex')

```
## Error Report
```
file encoding: UTF-8
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-6-62dc1e1ae97a> in <module>()
     15 
     16 
---> 17 tikz_save('mytikz.tex')
     18 
     19 #tikz_save(

/home/tim/anaconda3/lib/python3.5/site-packages/matplotlib2tikz/save.py in save(filepath, figure, encoding, figurewidth, figureheight, textsize, tex_relative_path_to_data, strict, wrap, extra, dpi, show_info)
    141 
    142     # gather the file content
--> 143     data, content = _recurse(data, figure)
    144 
    145     # Check if there is still an open groupplot environment. This occurs if not

/home/tim/anaconda3/lib/python3.5/site-packages/matplotlib2tikz/save.py in _recurse(data, obj)
    250             data['extra axis options'] = set()
    251 
--> 252             ax = axes.Axes(data, child)
    253             if not ax.is_colorbar:
    254                 # Run through the child objects, gather the content.

/home/tim/anaconda3/lib/python3.5/site-packages/matplotlib2tikz/axes.py in __init__(self, data, obj)
    149             pass
    150         else:
--> 151             assert yaxis_pos == 'right'
    152             self.axis_options.append('axis y line=right')
    153 

AssertionError: 
```

**Comment by nschloe** [comment]
@TKaluza That's a different issue that warrants a separate report. If you could just copy-paste your text into a new issue, that'd be great.

**Comment by DF3AK** [comment]
Is the problem solved meanwhile? I get the same error as TKaluza and whllnd whenever I try to export a 3D figure.

**Comment by nschloe** [comment]
@DF3AK The issue you're referring to is https://github.com/nschloe/matplotlib2tikz/issues/140.

**Comment by strpeter** [comment]
Can you please write in the readme or wiki that you don't support 3d plots? It took me a while of debugging to find it out. Thanks! ;)

**Comment by svretina** [comment]
is this error solved? I get the same error message when trying to save a 3d plot

Traceback (most recent call last):
  File "./surface_fit.py", line 472, in <module>
    tikz.save("./figures/surface.tex")
  File "/usr/local/lib/python3.6/site-packages/matplotlib2tikz/save.py", line 197, in save
    code = get_tikz_code(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/matplotlib2tikz/save.py", line 160, in get_tikz_code
    data, content = _recurse(data, figure)
  File "/usr/local/lib/python3.6/site-packages/matplotlib2tikz/save.py", line 280, in _recurse
    ax = axes.Axes(data, child)
  File "/usr/local/lib/python3.6/site-packages/matplotlib2tikz/axes.py", line 150, in __init__
    assert yaxis_pos == 'right'
AssertionError

**Comment by nschloe** [comment]
@svretina Not solved, it's a matplotlib issue. See above.

**Comment by AlexSchwabauer** [comment]
@nschloe the latest reply in the issue that you linked suggests using the property `_offsets3d`. Is this something this library can do as long there is no official answer?
Here's the link to the reply: https://github.com/matplotlib/matplotlib/issues/7243#issuecomment-581045658

**Comment by nschloe** [comment]
Sure, whatever works.
