### ISSUE TITLE
Unicode symbol in title or xlabel produce exception

### ISSUE THREAD

**Issue by andreassch** [nschloe/matplotlib2tikz#269]
Trying to export a plot with unicode symbols in title or labels using matplotlib2tikz 0.6.18 throws an exception. This can be reproduced with the following minimal example:
```python
# -*- coding: utf-8 -*-

from matplotlib import pyplot as plt
from matplotlib2tikz import save as tikz_save

plt.figure()
plt.axis()
plt.title(u'äöü')
plt.ylabel(u'$\delta$D (‰)')
tikz_save('matplotlib2tikz_unicode.tikz', encoding='utf8')
plt.show()
```
The Python output is:
```
=========================================================
Please add the following lines to your LaTeX preamble:

\usepackage[utf8]{inputenc}
\usepackage{fontspec} % This line only for XeLaTeX and LuaLaTeX
\usepackage{pgfplots}
=========================================================
Traceback (most recent call last):
  File "matplotlib2tikz_unicode.py", line 10, in <module>
    tikz_save('matplotlib2tikz_unicode.tikz', encoding='utf8')
  File "anaconda2/lib/python2.7/site-packages/matplotlib2tikz/save.py", line 214, in save
    code = get_tikz_code(*args, **kwargs)
  File "anaconda2/lib/python2.7/site-packages/matplotlib2tikz/save.py", line 177, in get_tikz_code
    data, content = _recurse(data, figure)
  File "anaconda2/lib/python2.7/site-packages/matplotlib2tikz/save.py", line 296, in _recurse
    ax = axes.Axes(data, child)
  File "anaconda2/lib/python2.7/site-packages/matplotlib2tikz/axes.py", line 39, in __init__
    self.axis_options.append("title={{{}}}".format(title))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
```

This bug can be fixed by making the strings `title={{{}}}`, `xlabel={{{}}}` and `ylabel={{{}}}` in axis.py unicode, as shown in the following diff:
```diff
--- axes.py.bak	2019-02-11 15:25:28.636874398 +0100
+++ axes.py	2019-02-11 15:25:33.104805255 +0100
@@ -36,15 +36,15 @@
         # get plot title
         title = obj.get_title()
         if title:
-            self.axis_options.append("title={{{}}}".format(title))
+            self.axis_options.append(u"title={{{}}}".format(title))
 
         # get axes titles
         xlabel = obj.get_xlabel()
         if xlabel:
-            self.axis_options.append("xlabel={{{}}}".format(xlabel))
+            self.axis_options.append(u"xlabel={{{}}}".format(xlabel))
         ylabel = obj.get_ylabel()
         if ylabel:
-            self.axis_options.append("ylabel={{{}}}".format(ylabel))
+            self.axis_options.append(u"ylabel={{{}}}".format(ylabel))
 
         # Axes limits.
         # Sort the limits so make sure that the smaller of the two is actually
```
With these changes, the minimal example runs through smoothly.

**Comment by andreassch** [comment]
Thanks for fixing this.

Followup: there is a similar problem in axes.py when having unicode symbols in ticklabels:
```
  File "anaconda2/lib/python2.7/site-packages/matplotlib2tikz/axes.py", line 577, in _get_ticks
    "{}ticklabels={{{}}}".format(xy, ",".join(pgfplots_ticklabels))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2212' in position 0: ordinal not in range(128)
```
It can be fixed similarly:
```
--- axes.py.bak	2019-08-09 14:23:06.681989329 +0200
+++ axes.py	2019-08-09 14:21:14.000000000 +0200
@@ -574,7 +574,7 @@
 
         if is_label_required:
             axis_options.append(
-                "{}ticklabels={{{}}}".format(xy, ",".join(pgfplots_ticklabels))
+                u"{}ticklabels={{{}}}".format(xy, ",".join(pgfplots_ticklabels))
             )
     return axis_options
```

**Comment by nschloe** [comment]
PR or new issue pls.
