### ISSUE TITLE
Crash when using mark: AttributeError: 'str' object has no attribute 'get_children'

### ISSUE THREAD

**Issue by Aikhjarto** [nschloe/matplotlib2tikz#292]
A crash occurs when using markevery. See MWE and stack trace below.
System: Windows 7
Python: 3.7.2
Matplotlib: 3.0.3
matplotlib2tikz: 0.7.3

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib2tikz
plt.plot(np.arange(-12,-2),-np.arange(10)+11,'x-',markersize=10, markevery=[2,7,9])
print(matplotlib2tikz.get_tikz_code('test.tikz'))
```

```
> python bugreport_fixed_matplotlib2tikz_markevery2.py
Traceback (most recent call last):
  File "bugreport_fixed_matplotlib2tikz_markevery2.py", line 5, in <module>
    print(matplotlib2tikz.get_tikz_code('test.tikz'))
  File "(...)\lib\site-packages\matplotlib2tikz\save.py", line 188, in get_tikz_code
    data, content = _recurse(data, figure)
  File "(...)\lib\site-packages\matplotlib2tikz\save.py", line 324, in _recurse
    for child in obj.get_children():
AttributeError: 'str' object has no attribute 'get_children'
```

**Comment by nschloe** [comment]
`get_tikz_code` doesn't have a filename argument.
