### ISSUE TITLE
TypeError: not enough arguments for format string on line 1203

### ISSUE THREAD

**Issue by mverleg** [nschloe/matplotlib2tikz#35]
This simple example:
```
fig, ax = subplots()
ax.scatter(linspace(0, 100, 101), linspace(0, 100, 101) + 15 * rand(101))
tikz_save('test.tikz')
```
Raises this exception:
```
file encoding: None
Traceback (most recent call last):
  File ".../tikz_test.py", line 9, in <module>
    tikz_save('test.tikz')
  File ".../matplotlib2tikz.py", line 152, in save
    data, content = _handle_children( data, mpl.pyplot.gcf() )
  File ".../matplotlib2tikz.py", line 1520, in _handle_children
    data, cont = _draw_axes( data, child )
  File ".../matplotlib2tikz.py", line 437, in _draw_axes
    data, children_content = _handle_children( data, obj )
  File ".../matplotlib2tikz.py", line 1538, in _handle_children
    data, cont = _draw_pathcollection( data, child )
  File ".../matplotlib2tikz.py", line 1147, in _draw_pathcollection
    draw_options = do
  File ".../matplotlib2tikz.py", line 1203, in _draw_path
    % tuple( vert )
TypeError: not enough arguments for format string
```
Using today's version of the script and Python 2.7.3

It seems like a bug to me; is it?

**Comment by nschloe** [comment]
This fix for this just went in, cf. https://github.com/nschloe/matplotlib2tikz/commit/df6e2cf6d5456073e4dfeeaf84519b45a0566f55. Will be part of the next release.
