### ISSUE TITLE
matplotlib2tikz v0.5.0 missing matplotlib2tikz module

### ISSUE THREAD

**Issue by televator** [nschloe/matplotlib2tikz#74]
When I try to pip-install matplotlib2tikz, pip complains about the missing matplotlib2tikz module.
```
$ pip install matplotlib2tikz # used pip3 on my system
Downloading/unpacking matplotlib2tikz
  Downloading matplotlib2tikz-0.5.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/matplotlib2tikz/setup.py) egg_info for package matplotlib2tikz
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/matplotlib2tikz/setup.py", line 7, in <module>
        from matplotlib2tikz import __version__, __license__, __author__, __email__
    ImportError: No module named 'matplotlib2tikz'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/matplotlib2tikz/setup.py", line 7, in <module>

    from matplotlib2tikz import __version__, __license__, __author__, __email__

ImportError: No module named 'matplotlib2tikz'
```

The tar seems to be missing the essential module, cf. manual download:
```
$ ls matplotlib2tikz-0.5.0     
PKG-INFO  setup.py  test
```

Worked around by pulling from github, which installs perfectly fine.
Kindly let me know if this is not reproducable for you, cheers.

**Comment by nschloe** [comment]
Thanks for the report. Should be fixed now (0.5.1).
